"""add messages table

Revision ID: 5408c6b22b05
Revises: 64a1df4292e6
Create Date: 2026-09-17 22:32:33.503831
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '5408c6b22b05'
down_revision: str | None = '64a1df4292e6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gym_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.Column('member_name', sa.String(length=160), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('detail', sa.String(length=255), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('related_date', sa.Date(), nullable=True),
    sa.Column('sent_by_user_id', sa.Integer(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['gym_id'], ['gyms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sent_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index('ix_messages_gym_created', ['gym_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_gym_id'), ['gym_id'], unique=False)
        batch_op.create_index('ix_messages_gym_member', ['gym_id', 'member_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index('ix_messages_gym_member')
        batch_op.drop_index(batch_op.f('ix_messages_gym_id'))
        batch_op.drop_index('ix_messages_gym_created')

    op.drop_table('messages')
    # ### end Alembic commands ###
